#if COM_UNITY_ML_AGENTS
using KaijuSolutions.Agents.Extensions;
using KaijuSolutions.Agents.Sensors;
using Unity.MLAgents.Sensors;
using UnityEngine;

namespace KaijuSolutions.Agents.Learning
{
    /// <summary>
    /// Integrate <see cref="KaijuSolutions.Agents.Sensors.KaijuVisionSensor{T}"/>s with <see href="https://docs.unity3d.com/Packages/com.unity.ml-agents@latest">ML-Agents</see>. All positions are normalized from negative one to positive one based on detection distance.
    /// </summary>
#if UNITY_EDITOR
    [AddComponentMenu("Kaiju Solutions/Agents/ML-Agents/Sensors/Kaiju Learning Vision Sensor", 1)]
    [Icon("Packages/ca.kaijusolutions.agents/Editor/Icon.png")]
    [HelpURL("https://agents.kaijusolutions.ca/manual/ml-agents.html")]
#endif
    [RequireComponent(typeof(KaijuVisionSensor<Component>))]
    public class KaijuLearningVisionSensor : KaijuLearningSensor
    {
        /// <summary>
        /// The <see cref="KaijuSolutions.Agents.Sensors.KaijuVisionSensor{T}"/>. Do not modify the properties of this sensor at runtime.
        /// </summary>
#if UNITY_EDITOR
        [Tooltip("The vision sensor. Do not modify the properties of this sensor at runtime.")]
#endif
        [SerializeField]
        private KaijuVisionSensor<Component> sensor;
        
        /// <summary>
        /// The maximum number of observations we can detect the positions of. Do not modify this at runtime.
        /// </summary>
#if UNITY_EDITOR
        [Tooltip("The maximum number of observations we can detect the positions of. Do not modify this at runtime.")]
#endif
        [Min(1)]
        [SerializeField]
        private int number = 1;
        
        /// <summary>
        /// If the nearest or the furthest observations should be observed.
        /// </summary>
#if UNITY_EDITOR
        [Tooltip("If the nearest or the furthest observations should be observed.")]
#endif
        [SerializeField]
        private bool farthest;
        
        /// <summary>
        /// How to handle breaking ties on angles when the distance is the same.
        /// </summary>
#if UNITY_EDITOR
        [Tooltip("How to handle breaking ties on angles when the distance is the same.")]
#endif
        [SerializeField]
        private KaijuAngleSortMode sorting = KaijuAngleSortMode.Magnitude;
        
        /// <summary>
        /// If the Y-position of the observed instances should be included, or otherwise just the X and Z positions. Do not modify this at runtime.
        /// </summary>
#if UNITY_EDITOR
        [Tooltip("If the Y-position of the observed instances should be included, or otherwise just the X and Z positions. Do not modify this at runtime.")]
#endif
        [SerializeField]
        private bool height;
#if UNITY_EDITOR
        /// <summary>
        /// Editor-only function that Unity calls when the script is loaded or a value changes in the Inspector.
        /// </summary>
        private void OnValidate()
        {
            if (sensor == null || sensor.gameObject != gameObject)
            {
                sensor = GetComponent<KaijuVisionSensor<Component>>();
            }
        }
#endif
        /// <summary>
        /// Returns a description of the observations that will be generated by the sensor.
        /// </summary>
        /// <returns>An object describing the observation.</returns>
        public override ObservationSpec GetObservationSpec()
        {
            return ObservationSpec.VariableLength(height ? 3 : 2, number);
        }
        
        /// <summary>
        /// Write the observation data. Note that this may be called multiple times per agent step, so should not mutate any internal state.
        /// </summary>
        /// <param name="writer">Where the observations will be written to.</param>
        /// <returns>The number of elements written.</returns>
        public override int Write(ObservationWriter writer)
        {
            // If there is nothing to do if nothing is observed.
            int total;
            if (sensor.Observed.Count < 1)
            {
                total = number * (height ? 3 : 2);
                for (int i = 0; i < total; i++)
                {
                    writer[i] = 0f;
                }
                
                return total;
            }
            
            // If it is just one instance, get it directly to not waste resources sorting.
            if (number < 2)
            {
                if (height)
                {
                    writer.Add(farthest ? sensor.FarthestPosition3(true) : sensor.NearestPosition3(true));
                    return 3;
                }
                
                Vector2 target = farthest ? sensor.FarthestPosition(true) : sensor.NearestPosition(true);
                writer[0] = target.x;
                writer[1] = target.y;
                return 2;
            }
            
            // Otherwise, get the sorted instances.
            int wrote = 0;
            if (height)
            {
                Vector3[] p3 = sensor.SortDistance3Position3(farthest, sorting, true);
                int upper = Mathf.Min(p3.Length, number);
                for (int i = 0; i < upper; i++)
                {
                    writer.Add(p3[i], wrote);
                    wrote += 3;
                }
                
                total = number * 3;
            }
            else
            {
                Vector2[] p2 = sensor.SortDistancePosition(farthest, sorting, true);
                int upper = Mathf.Min(p2.Length, number);
                for (int i = 0; i < upper; i++)
                {
                    writer[wrote++] = p2[i].x;
                    writer[wrote++] = p2[i].y;
                }
                
                total = number * 2;
            }
            
            // Pad the remainder with nothing.
            while (wrote < total)
            {
                writer[wrote++] = 0f;
            }
            
            return total;
        }
    }
}
#endif