#if COM_UNITY_ML_AGENTS
using Unity.MLAgents.Sensors;
using UnityEngine;

namespace KaijuSolutions.Agents.Learning
{
    /// <summary>
    /// Sensor for getting the normalized <see cref="KaijuSolutions.Agents.KaijuAgent.Velocity"/> of an <see cref="KaijuSolutions.Agents.KaijuAgent"/> for <see href="https://docs.unity3d.com/Packages/com.unity.ml-agents@latest">ML-Agents</see>.
    /// </summary>
    [DisallowMultipleComponent]
#if UNITY_EDITOR
    [AddComponentMenu("Kaiju Solutions/Agents/ML-Agents/Sensors/Kaiju Learning Velocity Sensor", 2)]
    [Icon("Packages/ca.kaijusolutions.agents/Editor/Icon.png")]
    [HelpURL("https://agents.kaijusolutions.ca/manual/ml-agents.html")]
#endif
    public class KaijuLearningVelocitySensor : KaijuLearningAgentSensor
    {
        /// <summary>
        /// If the velocity should be relative to the <see cref="KaijuLearningAgentSensor.Agent"/>'s heading or in world-space.
        /// </summary>
#if UNITY_EDITOR
        [Tooltip("If the velocity should be relative to the agent's heading or in world-space.")]
#endif
        [SerializeField]
        private bool relative = true;
        
        /// <summary>
        /// Returns a description of the observations that will be generated by the sensor.
        /// </summary>
        /// <returns>An object describing the observation.</returns>
        public override ObservationSpec GetObservationSpec() => ObservationSpec.Vector(2);
        
        /// <summary>
        /// Write the observation data. Note that this may be called multiple times per agent step, so should not mutate any internal state.
        /// </summary>
        /// <param name="writer">Where the observations will be written to.</param>
        /// <returns>The number of elements written.</returns>
        public override int Write(ObservationWriter writer)
        {
            Vector2 vector = (relative ? Agent.RelativeVelocity : Agent.Velocity) / Agent.MoveSpeed;
            writer[0] = vector.x;
            writer[1] = vector.y;
            return 2;
        }
    }
}
#endif