#if COM_UNITY_ML_AGENTS
using Unity.MLAgents.Sensors;
using UnityEngine;

namespace KaijuSolutions.Agents.Learning
{
    /// <summary>
    /// Sensor for getting the rotations of an <see cref="KaijuSolutions.Agents.KaijuAgent"/> for <see href="https://docs.unity3d.com/Packages/com.unity.ml-agents@latest">ML-Agents</see> normalized between zero and one.
    /// </summary>
    [DisallowMultipleComponent]
    [RequireComponent(typeof(KaijuAgent))]
#if UNITY_EDITOR
    [AddComponentMenu("Kaiju Solutions/Agents/ML-Agents/Sensors/Kaiju Learning Vision Sensor", 3)]
    [Icon("Packages/ca.kaijusolutions.agents/Editor/Icon.png")]
    [HelpURL("https://agents.kaijusolutions.ca/manual/ml-agents.html")]
#endif
    public class KaijuLearningRotationSensor : KaijuLearningAgentSensor
    {
        /// <summary>
        /// If there is a <see href="https://docs.unity3d.com/Manual/class-transform.html">transform</see>. in the world that the rotation should be relative to.
        /// </summary>
#if UNITY_EDITOR
        [Tooltip("If there is a transform in the world that the rotation should be relative to.")]
#endif
        public Transform relative;
        
        /// <summary>
        /// Returns a description of the observations that will be generated by the sensor.
        /// </summary>
        /// <returns>An object describing the observation.</returns>
        public override ObservationSpec GetObservationSpec() => ObservationSpec.Vector(1);
        
        /// <summary>
        /// Write the observation data. Note that this may be called multiple times per agent step, so should not mutate any internal state.
        /// </summary>
        /// <param name="writer">Where the observations will be written to.</param>
        /// <returns>The number of elements written.</returns>
        public override int Write(ObservationWriter writer)
        {
            writer[0] = transform ? Mathf.DeltaAngle(relative.eulerAngles.y, Agent.OrientationY) : Agent.OrientationY / 360f;
            return 1;
        }
    }
}
#endif