#if COM_UNITY_ML_AGENTS
using KaijuSolutions.Agents.Sensors;
using Unity.MLAgents.Sensors;
using UnityEngine;

namespace KaijuSolutions.Agents.Learning
{
    /// <summary>
    /// Integrate <see cref="KaijuCastSensor"/>s with <see href="https://docs.unity3d.com/Packages/com.unity.ml-agents@latest">ML-Agents</see>. This normalizes all rays from zero to one.
    /// </summary>
#if UNITY_EDITOR
    [AddComponentMenu("Kaiju Solutions/Agents/ML-Agents/Sensors/Kaiju Learning Cast Sensor", 0)]
    [Icon("Packages/ca.kaijusolutions.agents/Editor/Icon.png")]
    [HelpURL("https://agents.kaijusolutions.ca/manual/ml-agents.html")]
#endif
    [RequireComponent(typeof(KaijuCastSensor))]
    public class KaijuLearningCastSensor : KaijuLearningSensor
    {
        /// <summary>
        /// The <see cref="KaijuCastSensor"/>. Do not modify the properties of this sensor at runtime.
        /// </summary>
#if UNITY_EDITOR
        [Tooltip("The cast sensor. Do not modify the properties of this sensor at runtime.")]
#endif
        [SerializeField]
        private KaijuCastSensor sensor;
        
        /// <summary>
        /// The type of information collected by this sensor. Do not modify this at runtime.
        /// </summary>
#if UNITY_EDITOR
        [Tooltip("The type of information collected by this sensor. Do not modify this at runtime.")]
#endif
        [SerializeField]
        private ObservationType observation;
        
        /// <summary>
        /// Editor-only function that Unity calls when the script is loaded or a value changes in the Inspector.
        /// </summary>
        private void OnValidate()
        {
            if (sensor != null && sensor.gameObject == gameObject)
            {
                return;
            }
            
            sensor = GetComponent<KaijuCastSensor>();
#if UNITY_EDITOR
            if (!Application.isPlaying)
            {
                return;
            }
#endif
            if (sensor == null)
            {
                gameObject.AddComponent<KaijuCastSensor>();
            }
        }
        
        /// <summary>
        /// Returns a description of the observations that will be generated by the sensor.
        /// </summary>
        /// <returns>An object describing the observation.</returns>
        public override ObservationSpec GetObservationSpec()
        {
            OnValidate();
            return ObservationSpec.Vector(sensor.Casts, observation);
        }
        
        /// <summary>
        /// Write the observation data. Note that this may be called multiple times per agent step, so should not mutate any internal state.
        /// </summary>
        /// <param name="writer">Where the observations will be written to.</param>
        /// <returns>The number of elements written.</returns>
        public override int Write(ObservationWriter writer)
        {
            // Write the distances on a scale of zero to one.
            int i = 0;
            foreach (float distance in sensor.Distances(true))
            {
                writer[i++] = distance;
            }
            
            return i;
        }
    }
}
#endif