#if COM_UNITY_ML_AGENTS
using Unity.MLAgents.Sensors;
using UnityEngine;

namespace KaijuSolutions.Agents.Learning
{
    /// <summary>
    /// Base class for integrating all sensors with <see href="https://docs.unity3d.com/Packages/com.unity.ml-agents@latest">ML-Agents</see>.
    /// </summary>
#if UNITY_EDITOR
    [Icon("Packages/ca.kaijusolutions.agents/Editor/Icon.png")]
    [HelpURL("https://agents.kaijusolutions.ca/manual/ml-agents.html")]
#endif
    public abstract class KaijuLearningSensor : SensorComponent, ISensor
    {
        /// <summary>
        /// Create the ISensors. This is called by the Agent when it is initialized.
        /// </summary>
        /// <returns>Created ISensor objects.</returns>
        public override ISensor[] CreateSensors() => new ISensor[] { this };
        
        /// <summary>
        /// Returns a description of the observations that will be generated by the sensor.
        /// </summary>
        /// <returns>An object describing the observation.</returns>
        public abstract ObservationSpec GetObservationSpec();
        
        /// <summary>
        /// Write the observation data. Note that this may be called multiple times per agent step, so should not mutate any internal state.
        /// </summary>
        /// <param name="writer">Where the observations will be written to.</param>
        /// <returns>The number of elements written.</returns>
        public abstract int Write(ObservationWriter writer);
        
        /// <summary>
        /// Return a compressed representation of the observation. For small observations, this should generally not be implemented. However, compressing large observations (such as visual results) can significantly improve model training time. Note that this may be called multiple times per agent step, so should not mutate any internal state.
        /// </summary>
        /// <returns>Compressed observation.</returns>
        public virtual byte[] GetCompressedObservation() => null;
        
        /// <summary>
        /// Return information on the compression type being used.
        /// </summary>
        /// <returns>An object describing the compression used by the sensor.</returns>
        public virtual CompressionSpec GetCompressionSpec() => CompressionSpec.Default();
        
        /// <summary>
        /// Get the name of the sensor. This is used to ensure deterministic sorting of the sensors on an Agent, so the naming must be consistent across all sensors and agents.
        /// </summary>
        /// <returns>The name of the sensor.</returns>
        public string GetName()
        {
            // Get the parents depth to add to the ordering for consistency.
            int parents = 0;
            Transform parent = transform.parent;
            while (parent != null)
            {
                parents++;
                parent = parent.parent;
            }
            
            // Write the classes' full name, the depth of this being the parents, where it sits relative to other components, how many children this has, and as long as its not the root (given the agent name may be dynamic at runtime), add the name of the object.
            return $"{GetType().FullName} {parents} {transform.GetSiblingIndex()} {transform.childCount} {(parents > 0 ? $" {name}" : string.Empty)}";
        }
        
        /// <summary>
        /// Update any internal state of the sensor. This is called once per each agent step.
        /// </summary>
        public virtual void Update() { }
        
        /// <summary>
        /// Resets the internal state of the sensor. This is called at the end of an Agent's episode. Most implementations can leave this empty.
        /// </summary>
        public virtual void Reset() { }
    }
}
#endif